lyrics = [["Maybe way ston com",
"De figure ways ou",
"De full",
"Sindefay com beller",
"Tou ta the faw",
"Ti ka fun",
"Dic different bomsto lama",
"Dic fsins so bo fa",
"Miway",
"Touway",
"Com fo baybe",
"Ouahahaah ahaha ahaha",
"Ouahahaah ahaha ahaha"],
["The cray febel is hye bull its over",
"gabaybe a laysay iii the cray fuick be ai i",
"fink a bay fom sows on a li a coll sii a",
"bay forss a bay simfis a lii toossai eav",
"binn siii aye kry off tings",
"Bay the payfed kiz lii a nkus gowey si gowey",
"Kry a single li a fayking aye a li a lay lay lay lay on a lay on a lay",
"li an on alone",
"Kry a single li a fayking aye a liii a lay lay lay lay on a lay on a lay"],
["Ey da oui eu wa e",
"a way to see",
"Gonna way to see com a lie",
"De scan beu me goway bike alone",
"sikebow",
"Coulou bay fan",
"Toulou bay cobay",
"Cobay Cobay Some way",
"Coulou way Bo way",
"Cousou sam a law.",
"La la laalala diga diga"],
["The kun sun a go away a",
"better way sun a bouai over say",
"a call ay tever go away go away",
"a beller a beller bidoual bellerthen",
"go way scan california scum a",
"sufer do way a go one balala",
"beller da sufer",
"bidoual bellerthen",
"bidoual bellerthen",
"bidoual bellerthen",
"bidoual bellerthen",
"bidoual bellerthen",
"bidoual bellerthen",
"bidoual bellerthen"],
["Pien ow",
"Soucun Face",
"Ouma ayy",
"Juduway",
"Somay caunt",
"One Awas Soucun Face",
"soum ay",
"duy cow bay",
"your aunt",
"anawant",
"maaaa",
"Mmmmmmhh",
"Cun ayy euzeus",
"Cow",
"Mieusss",
"Pero",
"Belby si ca",
"Pero herpe dela po"]]

recognized_lyrics = [["maybe ways domed calm",
"the finger at ways you",
"the form",
"sind of fate combatant",
"on two dozen phoned",
"the cash on",
"the deck did errands bombs still none of the",
"dressings sobel filed",
"the way",
"to win or",
"counsel david",
"well ha ha ha ha ha ha ha ha ha",
"who was ha ha ha ha ha ha ha ha"],
["mccrae said though is tied boom it's so good",
"debate it and they say that guy is a crate if we can beat i",
"kind of thing today foam so who's on monday a cozy out the salsa",
"bay since this is a suicide at ease",
"dean c. i. trial of things",
"they said they saved jews city and youth go we'd see go we know",
"chi is in a line of sight thing i had lived and i'm lying lying lying on that lay on the line",
"that i acted alone",
"cries in the line of thanking god that i can i live the lying on a lady on the night"],
["hey don't we use our way no",
"way to see",
"the no way to stay calm",
"island this guy and you go away by two known",
"side of bones",
"all the good of a son",
"today companies",
"kobe kobe some white",
"kuwait go away",
"too soon is on the note",
"that out loud loud about the get the death"],
["and and then ago way", 
"about that airway send the blue whales",
"as a cold light never go away go away",
"cabana about them they do want beth and",
"go ways can cut the phone ask them and sell",
"that to waco wambaugh allow that medicine so",
"they do well denizen",
"the two wound that is",
"in the do what the eyes n. b.",
"you want a balanced",
"than the one benefit",
"the weapon and then",
"the two and a bed offend",
"you want benefit"],
["yeah now soup in facing",
"whom i",
"do it",
"so late counts",
"wanna was sukru face",
"soon i'm",
"doing kobe",
"your pounds",
"ana winds",
"are",
"map only",
"conway to do this",
"to go",
"mute their",
"frodo",
"b. c. come",
"out there or",
"at the the pope"],
]