fonts = ["Bluu Next",
"Courier 10 Pitch",
"Hack",
"Ubuntu",
"DejaVu Sans",
"DejaVu Sans Mono",
"DejaVu Serif",
"FreeMono",
"FreeSans",
"FreeSerif",
"Liberation Mono",
"Liberation Sans",
"Liberation Sans Narrow",
"Liberation Serif",
"Nimbus Mono PS",
"Nimbus Sans",
"Nimbus Sans Narrow",
"Noto Mono",
"Ubuntu Condensed",
"Ubuntu Mono",
"Droid Sans Fallback",
"Mitra Mono"]