lyrics = [["Maybe way ston com",
"De figure ways ou",
"De full",
"Sindefay com beller",
"Tou ta the faw",
"Ti ka fun",
"Dic different bomsto lama",
"Dic fsins so bo fa",
"Miway",
"Touway",
"Com fo baybe",
"Ouahahaah ahaha ahaha",
"Ouahahaah ahaha ahaha"],
["The cray febel is hye bull its over",
"gabaybe a laysay iii the cray fuick be ai i",
"fink a bay fom sows on a li a coll sii a",
"bay forss a bay simfis a lii toossai eav",
"binn siii aye kry off tings",
"Bay the payfed kiz lii a nkus gowey si gowey",
"Kry a single li a fayking aye a li a lay lay lay lay on a lay on a lay",
"li an on alone",
"Kry a single li a fayking aye a liii a lay lay lay lay on a lay on a lay"],
["Ey da oui eu wa e",
"a way to see",
"Gonna way to see com a lie",
"De scan beu me goway bike alone",
"sikebow",
"Coulou bay fan",
"Toulou bay cobay",
"Cobay Cobay Some way",
"Coulou way Bo way",
"Cousou sam a law.",
"La la laalala diga diga"],
["The kun sun a go away a",
"better way sun a bouai over say",
"a call ay tever go away go away",
"a beller a beller bidoual bellerthen",
"go way scan california scum a",
"sufer do way a go one balala",
"beller da sufer",
"bidoual bellerthen",
"bidoual bellerthen",
"bidoual bellerthen",
"bidoual bellerthen",
"bidoual bellerthen",
"bidoual bellerthen",
"bidoual bellerthen",
"bidoual bellerthen"],
["Pien ow",
"Soucun Face",
"Ouma ayy",
"Juduway",
"Somay caunt",
"One Awas Soucun Face",
"soum ay",
"duy cow bay",
"your aunt",
"anawant",
"maaaa",
"Mmmmmmhh",
"Cun ayy euzeus",
"Cow",
"Mieusss",
"Pero",
"Belby si ca",
"Pero herpe",
"Dela po"]]